### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by CodeCorrupt** [dkogan/gnuplotlib#11]
Can we please include some install instructions in the README? I've tried using `pip install gnuplotlib` which installs successfully, but when I try to import it it tells me that there is `No module named gnuplotlib`.

I'm relatively new to Python so I could also be missing something obvious...

**Comment by CodeCorrupt** [comment]
I managed to solve the issue. For some reason when it was installed through the `requirements.txt` it was different then if I installed it directly with `pip install gnuplotlib`.

I don't know if the issue lies on pip's side of gnuplotlib's so I'll leave this issue open at the discretion of the maintainer to close.

**Comment by dkogan** [comment]
On June 2, 2018 5:01:56 PM PDT, Tyler Hoyt <notifications@github.com> wrote:
>I managed to solve the issue. For some reason when it was installed
>through the `requirements.txt` it was different then if I installed it
>directly with `pip install gnuplotlib`.
>
>I don't know if the issue lies on pip's side of gnuplotlib's so I'll
>leave this issue open at the discretion of the maintainer to close.

Hi. The reason there're no install instructions is that it's supposed to work exactly like any other python package. But if something is broken, I want to fix it. What does "install through the 'requirements.txt'" mean? Is that the one that was broken, or was pip broken?

Thanks for the report

**Comment by CodeCorrupt** [comment]
I have been implementing it in a Docker container. In the build when I put the pip requirements in `requirements.txt` and run `pip install -r requirements.txt` as part of the image build I received the error. If I moved this outside the requirements and ran another build step in the Dockerfile of `pip install gnuplotlib` then it worked fine. I honestly have no idea what could cause the difference because my understanding is that using the `-r` flag effectively just cats the requirements file into `pip install`

**Comment by Schmetzler** [comment]
I have the same strange issue.
I installed gnuplotlib through pip it says `Successfully installed`... and afterwards i can't import it (and it does not appear in `pip list`)

**Comment by Schmetzler** [comment]
I maybe got some kind of reason, why this happens. It seems that it has to do with Debian-like systems (I run Ubuntu 16.04). Since everything is installed in dist-packeges not site-packages (and gnuplotlib is somehow installed in site-packages. Maybe some absolute paths?). See [https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages](https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages) for some kind of reference.

**Comment by Schmetzler** [comment]
After creating a wheel from source it works.
```
git clone https://github.com/dkogan/gnuplotlib.git
cd gnuplotlib
python setup.py sdist bdist_wheel install
cd dist
pip install gnuplotlib-0.20-py2-none-any.whl
```

**Comment by dkogan** [comment]
OK. I don't use any of those, but gnuplotlib isn't doing anything special, so it should work like any other module. You consistently see issues with gnuplotlib (installed via pip) but not with other modules (also installed via pip)?

**Comment by dkogan** [comment]
I need more information about this to make a comment. Please reopen if this is still causing trouble.
