### ISSUE TITLE
Any example script to get multiplot layout 

### ISSUE THREAD

**Issue by ganeshgore** [dkogan/gnuplotlib#13]
Gnuplot Multiplot Layout 
http://gnuplot.sourceforge.net/demo_5.2/layout.html

I tried simple script
`
import numpy as np
import gnuplotlib as gp

x = np.arange(101) - 50
g1 = gp.gnuplotlib(title='Test',
                   set=['format x "%0.2s%c"',
                        'multiplot layout 4, 1 title "Graph"'
                        ]
                   )
g1.plot(x, x**2)
g1.plot(x, x**3)
`

but gives following error 
`gnuplotlib.GnuplotlibError: Gnuplot error: '
QXcbConnection: XCB error: 145 (Unknown), sequence: 171, resource id: 0, major code: 139 (Unknown), minor code: 20
' while sending cmd 'set multiplot layout 4, 1 title 'Graph''`

**Comment by dkogan** [comment]
This is definitely not supported currently, since it breaks the
assumption of "one gnuplot plot command per plot". But I've had thoughts
recently of adding it, so this is apropos. Did you have ideas of what
would be a reasonable interface? How about this:

    p = gp.plot(multiplot='.....')   # The larger plot window
    p.multiplot( (x,y, _with='whatever')  # Subplot 0
                 ((x0,x1), (y0,y0),       # Subplot 1
                  _with = 'something else',
                   set= 'something'), )

So each item in the multiplot() call could be plotted on its own with
gp.plot(). Thoughts?

**Comment by ganeshgore** [comment]
Thank you for the quick response.
Multiplot support will be a very useful feature addition.
The approach you mentioned appears pretty straightforward and intuitive.
We can add a set argument in gp.multiplot also to set left, right and between graph margin.

**Comment by dkogan** [comment]
I just added experimental support for this feature. Look at the end of demo.py in the latest revision. This was a large change with potential to break previously-functional plotting. I think this works, but I haven't yet tested it sufficiently to do a new release. And there isn't any documentation. If you check out the latest, and test it (both for single and multiplots), that would be helpful.

**Comment by ganeshgore** [comment]
Sure, I will run couple of examples to validate

**Comment by dkogan** [comment]
Have you tried it? If not, can you please do that? I'd like to make a new release with this feature.

**Comment by dkogan** [comment]
OK, I claim this works, so I just made a release with this feature, and I'm closing this bug. If you try it and something doesn't work, please tell me.
