### ISSUE TITLE
make extract_Example.py bilingual

### ISSUE THREAD

**Issue by sandrotosi** [dkogan/gnuplotlib#14]
```
--- a/extract_README.py
+++ b/extract_README.py
@@ -24,7 +24,11 @@ exec( 'import {} as mod'.format(modname)
 
 import inspect
 import re
-import StringIO
+try:
+    from StringIO import StringIO ## for Python 2
+except ImportError:
+    from io import StringIO ## for Python 3
+
 
 def dirmod():
     r'''Same as dir(mod), but returns only functions, in the definition order'''
@@ -69,7 +73,7 @@ with open('README.org', 'w') as f_target
 
             prev_indented = False
 
-            sio = StringIO.StringIO(s)
+            sio = StringIO(s)
             for l in sio:
 
                 # handle links
```

will make that script able to run on py2 and py3k

**Comment by dkogan** [comment]
Thank you very much! I pushed the patch. Will update the Debian package to use python3 here with the next upstream upload.

**Comment by sandrotosi** [comment]
I've actually already taken care of porting the debian package to py3k, you can have a look at the full patch here: https://salsa.debian.org/python-team/modules/python-gnuplotlib/blob/master/debian/patches/make-py3k.patch

**Comment by dkogan** [comment]
Sandro Tosi <notifications@github.com> writes:

> I've actually already taken care of porting the debian package to
> py3k, you can have a look at the full patch here:
> https://salsa.debian.org/python-team/modules/python-gnuplotlib/blob/master/debian/patches/make-py3k.patch

Looks good. Thanks.
