### ISSUE TITLE
Capture output?

### ISSUE THREAD

**Issue by terhorst** [dkogan/gnuplotlib#17]
Nice library! Is it possible to capture the output into string instead of writing directly to stdout? Thanks!

**Comment by dkogan** [comment]
Probably. Which output are you talking about, specifically?

**Comment by terhorst** [comment]
Sorry, should have been more specific. I'm using your software to produce text plots via e.g. `terminal='dumb 80,40'`. Ideally, I would like to send these to a log file via the Python logging apparatus. However, right now they go directly to the console. I suppose one option would be to use `set output` inside of GNUplot, but maybe a cleaner solution is to use subprocess.PIPE?

**Comment by dkogan** [comment]
Ah, I see. It's already going to a file descriptor, so subprocess.PIPE doesn't do anything for me, I think. The best way I can think of doing this right now is something like this:

``` python
#!/usr/bin/python3
import numpy as np
import gnuplotlib as gp
import os

def getplot(*args, **plotoptions):

    FD_READ,FD_WRITE = os.pipe()
    os.set_inheritable(FD_WRITE, True)

    plot = gp.gnuplotlib(output = f'/dev/fd/{FD_WRITE}', **plotoptions)
    plot.plot(*args)
    del plot
    os.close(FD_WRITE)
    return open(f'/dev/fd/{FD_READ}', 'r').read()


s0 = getplot(np.arange(100)**2.,
             unset    = 'grid',
             terminal = 'dumb 80 40')
print(s0)

s1 = getplot(-np.arange(100)**2.,
             unset    = 'grid',
             terminal = 'dumb 80 40')
print(s1)

```

This works. But there're several annoyances here:

- the read end of the pipe is never closed, the write end isn't close if there's an error
- this is synchronous, so this works only if the plot data is smaller than the os buffer size. Probably will be true 99% of the time. But someday somebody will make a giant plot, and they'll wonder why plot() is blocking

I have a vague thought about a slightly better way, but maybe let me do that later. Does the above solve your problem in the meantime?

**Comment by terhorst** [comment]
I see, maybe it's not easier to pipe the output. In that case, I can just write the plot to a tempfile and read it back in. The log updates that include plots are infrequent enough that it won't matter, performance-wise.

**Comment by dkogan** [comment]
Yeah, this is just how it is. Gnuplot writes its output to a pipe, so you'd need code to pull it out, with all the wrinkles that come with that.
