### ISSUE TITLE
Greek fonts using epslatex terminal

### ISSUE THREAD

**Issue by zstreeter** [dkogan/gnuplotlib#19]
Hi there,

I really love gnuplot and have used it to generate nice plots with latex symbols for publication.  This is done with the epslatex terminal that generates two files, out.tex and out.eps.  The eps is the bare figure without the latex symbols and the tex document provides the tex symbols.  
I am saving the output as "hardcopy=out.tex" just like my gnuplot scipt.  The Greek symbols built into gnuplot work (e.g {/Symbol a} for alpha) but I am having a hard time reproducing the latex Greek symbols. 

Say I want a phi for the y axis label, then I have ylabel="$\phi$" in python using your plot command but this doesn't reproduce the Greek symbol.  I have tried $\\phi$ with two backslashes also, just in case, and this works using just gnuplot.

Any suggestions would be great!  Using this workflow would be awesome because I can use python to create actual publication quality figures with your program!

**Comment by dkogan** [comment]
Hi. You have two levels of stuff interpreting \: python and gnuplot. So you can either

- Use a python "raw" string to make python not interpret \
- Use an extra set of \

Either of these produce the plot you want:


```python
gp.plot( np.arange(5),
         output   = "tstfigure.tex",
         terminal = "epslatex",
         ylabel = "$\\\\phi$",
         )
```

```python
gp.plot( np.arange(5),
         output   = "tstfigure.tex",
         terminal = "epslatex",
         ylabel = r"$\\phi$",
         )
```

**Comment by dkogan** [comment]
I'm closing the bug. If you're still having problems, please reopen.

**Comment by zstreeter** [comment]
Yup that did it!  Thank you, I would not have know this!
