### ISSUE TITLE
Font size grainular control

### ISSUE THREAD

**Issue by zstreeter** [dkogan/gnuplotlib#20]
Hi,

I want to control each individual label, legend, etc font sizes just like in gnuplot.  I changed the font size for the whole picture in the terminal command like your demo but this creates large white-spaces and defeated the purpose for creating the larger font.  (Please see attached photo.)  I am using epslatex terminal for research papers FYI. 

The syntax in gnuplot is xlabel = "x axis" font ",20" and I am not sure how to did that with your interface. 

Thank you!

[graph.pdf](https://github.com/dkogan/gnuplotlib/files/4569619/graph.pdf)

**Comment by dkogan** [comment]
I don't follow. Can you include the python script that did the thing you
didn't like? And can you include the gnuplot script that DOES do what
you like, that you would like to get from python?

**Comment by zstreeter** [comment]
The pertinent python command that produced the graph.pdf I attached before is 

gp.plot(x,y, _with='lines', xlabel='R', ylabel=r'$\\phi$', terminal='epslatex font ",20"',
hardcopy='test.tex') 

and I have attached the gnuplot script.  But this global increase in font also created a lot of white-space between the symbols and the figure (even made a large white-space between the x-axis numbers and the figure), which doesn't look nice.  In gnuplot, you can set the font size of individual strings ( set xlabel "Matrix Size" font ",20") like in my script.  I was trying to do this because I thought this would give me larger fonts without the added large white-space.

So the main thing I would like is larger fonts but with appropriate amount of white-space needed for the larger character.  In gnuplot, creating larger fonts for the ylabel, for example, doesn't also push the label far to the left with too much white-space.  Does that make sense? 

[gnuplot_script.txt](https://github.com/dkogan/gnuplotlib/files/4569710/gnuplot_script.txt)

**Comment by dkogan** [comment]
OK. I ran some experiments, and I don't see the different text sizes.
But this is complicated, and I won't claim to understand the internals
of how gnuplot does this.

If all you want is to be able to do something like

  set xlabel "Matrix Size" font ",20"

you can say

  plot( ....,
        _set='xlabel "Matrix Size" font ",20" )

This should produce the desired gnuplot script. What do you see then?

**Comment by zstreeter** [comment]
Thank you for your help.  I ran some test and found the problem is within the Latex renderer for the fonts.  Setting your interface aside, I cannot create larger fonts after the Latex engine reproduces the fonts so I think it has something to do with the epslatex terminal creating a tex document from the gnuplot script and not recognizing the font command.  At any rate, I just looked at making a normal Gnuplot plot with your interface but without the post Latex rendered fonts and your _set command produced the expected result. 

What is the syntax for more than one string?  I have tried a few but keep getting syntax errors.  Something like
plot(...,
 _set='xlabel "Matrix Size" font ",20" ylabel "Percentage" font",30" title "Title" font ",40" ')
or how would you wright this?

**Comment by dkogan** [comment]
Zachary Streeter <notifications@github.com> writes:

> What is the syntax for more than one string?

  plot( _set=('stuff', 'other stuff') )

And the last time I used latex heavily was a long time ago, but it's
coming back to me now. You generally never pick fonts; that's something
you do in Word. There're some presets that are available that you can
use, however. For a single chunk of test, try this:

  xlabel = r'{\\Huge whatever}'

Or if you want to apply this to the whole plot, in your outer .tex file
do

  { \Huge \include{tstfigure} }

**Comment by zstreeter** [comment]
Okay great, thank you for your help!

It's definitely easier to just use the font from Gnuplot but it would be nice to have the more aesthetically pleasing Latex fonts.  I at least know how to approach what I want and the problems are not with your interface so thank you again!
