### ISSUE TITLE
Gnuplot process no longer responding when doing simple example gp.plot(x**2)

### ISSUE THREAD

**Issue by asanakoy** [dkogan/gnuplotlib#22]
Python 3.7, running an example script in tmux through ssh.

```
import numpy      as np                    
import gnuplotlib as gp                                   
                                           
x = np.arange(101) - 50                    
gp.plot(x**2)                  
```
Aslo tried passing `gp.plot(x**2, ascii=True)` with no success. 

Always get an error.
```
Traceback (most recent call last):
  File "test_ascii_plots1.py", line 6, in <module>
    gp.plot(x**2, ascii=True)
  File "/export/home/asanakoy/anaconda2/compgpu/envs/py3.7/lib/python3.7/site-packages/gnuplotlib.py", line 2654, in plot
    globalplot.plot(*curves)
  File "/export/home/asanakoy/anaconda2/compgpu/envs/py3.7/lib/python3.7/site-packages/gnuplotlib.py", line 2552, in plot
    plot_process_footer()
  File "/export/home/asanakoy/anaconda2/compgpu/envs/py3.7/lib/python3.7/site-packages/gnuplotlib.py", line 2385, in plot_process_footer
    self._checkpoint('printwarnings')
  File "/export/home/asanakoy/anaconda2/compgpu/envs/py3.7/lib/python3.7/site-packages/gnuplotlib.py", line 1720, in _checkpoint
    and/or gnuplot itself. Please report this as a gnuplotlib bug''')
gnuplotlib.GnuplotlibError: Gnuplot process no longer responding. This is likely a bug in gnuplotlib
and/or gnuplot itself. Please report this as a gnuplotlib bug
```

**Comment by dkogan** [comment]
I'm guessing this has something to do with your system or gnuplot install, but that error message is really not great here. Please try this:

Add `hardcopy='/tmp/tst.gp'` to the kwargs. The `plot()` function should then write to that file, and exit succesfully. This file is a gnuplot script. When you run it, you should get a plot, but I bet on your machine that won't happen. Can you let me know what does happen?

**Comment by dkogan** [comment]
Reading your email more closely, I maybe get a sense of what you're doing. Are you x-forwarding over ssh? Is it slow and/or broken? What if you run "xeyes"? Does it work?

**Comment by asanakoy** [comment]
It is not slow, and I don't do any X forwarding. 
`xeyes` doesn't work obviously.

I didn't know that Gnuplot requires X to be enabled. I was hoping to be able to just print plots in a terminal without any GUI.

**Comment by dkogan** [comment]
Gnuplot has plenty of backends that don't require X, but by default it tries to produce an interactive, graphical plot, which does use X. You want the "dumb" terminal. Do this:

```
import numpy      as np
import gnuplotlib as gp

x = np.arange(101) - 50
gp.plot(x**2, terminal = 'dumb 80,40')
```

I would like to improve the error message, though. Can you please run "gnuplot" and then do "plot x"? It will presumably fail, but I'd like to know if it hangs or reports an error or what. And it you can tell me what "show terminal" says, that'd be super.
