### ISSUE TITLE
A stupid question

### ISSUE THREAD

**Issue by linwaytin** [dkogan/gnuplotlib#24]
This looks great, as it combines the power of python and gnuplot!

I have a stupid question. The most basic command in gnuplot is `plot 'file.dat' using 1:2`.
How do I do this in `gnuplotlib`? Maybe I missed it but I couldn't find it in the documentation. Thanks.

**Comment by dkogan** [comment]
I don't understand the question. gnuplotlib plots numpy arrays. So load your file into a numpy array, and you can plot it. Does [the guide](https://github.com/dkogan/gnuplotlib/blob/master/guide/guide.org) not give you examples  that match what you want to do?

**Comment by linwaytin** [comment]
Thanks. I think I misunderstood this tool.
