### ISSUE TITLE
support logscale

### ISSUE THREAD

**Issue by jasondet** [dkogan/gnuplotlib#25]
I would like to be able to set axes to have log scales
http://gnuplot.info/docs_5.5/loc12373.html
Can you implement it?

**Comment by dkogan** [comment]
It's implemented:

```
plot(..., _set = 'logscale x')
```

Let me know if there's an issue.

**Comment by maruel** [comment]
It'd be great if one of the examples used `_set='logscale y'`.
As someone unfamiliar with gnuplot, I had to find this issue to figure this out.

Thanks a lot for the library!
