### ISSUE TITLE
does anyone run this on windows 7?

### ISSUE THREAD

**Issue by retsyo** [dkogan/gnuplotlib#6]
I have gnuplot(which is on my PATH environment places), but

```
E:\greensoft\math\gnuplot\bin>set path=E:\greensoft\math\gnuplot\bin;%path%

E:\greensoft\math\gnuplot\bin>gnuplot --version
gnuplot 5.1 patchlevel 0

E:\greensoft\math\gnuplot\bin>py27

E:\greensoft\math\gnuplot\bin>e:\prg\py\Anaconda2_32\python.exe
Python 2.7.12 |Anaconda 2.2.0 (32-bit)| (default, Jun 29 2016, 11:42:13) [MSC v.
1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy      as np
>>> import gnuplotlib as gp
>>>
>>> x = np.arange(101) - 50
>>> gp.plot(x**2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\prg\py\pure_pylib\_chart\_gnuplotlib\gnuplotlib.py", line 1678, in pl
ot
    globalplot = gnuplotlib(**plotOptions)
  File "e:\prg\py\pure_pylib\_chart\_gnuplotlib\gnuplotlib.py", line 792, in __i
nit__
    self._startgnuplot()
  File "e:\prg\py\pure_pylib\_chart\_gnuplotlib\gnuplotlib.py", line 812, in _st
artgnuplot
    self._safelyWriteToPipe("set terminal push", 'terminal')
  File "e:\prg\py\pure_pylib\_chart\_gnuplotlib\gnuplotlib.py", line 1029, in _s
afelyWriteToPipe
    errorMessage, warnings = self._checkpoint('printwarnings')
  File "e:\prg\py\pure_pylib\_chart\_gnuplotlib\gnuplotlib.py", line 1108, in _c
heckpoint
    rlist,wlist,xlist = select.select([self.gnuplotProcess.stderr],[], [], 5)
select.error: (10038, '')
```

**Comment by dkogan** [comment]
Hi. I do not use Windows. If you want to debug this, we can talk about
merging whatever patches you come up with. But I'm afraid that's all I
can offer.

dima

**Comment by retsyo** [comment]
well, I found which caused this problem on windows
```python
>>> print select.select.__doc__
select(rlist, wlist, xlist[, timeout]) -> (rlist, wlist, xlist)

*** IMPORTANT NOTICE ***
On Windows and OpenVMS, only sockets are supported; on Unix, all file
descriptors can be used.
```

**Comment by dkogan** [comment]
retsyo <notifications@github.com> writes:

> well, I found which caused this problem on windows
>
>>>> print select.select.__doc__
> select(rlist, wlist, xlist[, timeout]) -> (rlist, wlist, xlist)
>
> *** IMPORTANT NOTICE ***
> On Windows and OpenVMS, only sockets are supported; on Unix, all file
> descriptors can be used.

Thanks for tracking down. I'm using a select() to get a blocking read()
that times out after some amount of time has elapsed without any data
being read. Do you know how to get this in Windows?

**Comment by dkogan** [comment]
Windows support will only happen if somebody-not-me implements it. This report has gone untouched for 3 years, so this reporter also isn't the person who's going to implement it, and I'm closing this issue. There's a work in progress here: https://github.com/dkogan/gnuplotlib/pull/15
