### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by steview2000** [dkogan/gnuplotlib#7]
Very nice library. Thanks!

It seems that the default configuration file for gnuplot in ~/.gnuplot is ignored. I suggest to set as a default:
cmds = 'load \"~/.gnuplot\"'

**Comment by dkogan** [comment]
steview2000 <notifications@github.com> writes:

> It seems that the default configuration file for gnuplot in ~/.gnuplot is
> ignored.

Hi. I don't think this is true. Why do you think it is happening?


> I suggest to set as a default: cmds = 'load \"~/.gnuplot\"'

It's gnuplot's job to do this, and I shouldn't need to. Let's try to
understand the problem a bit better first.

dima

**Comment by steview2000** [comment]
Thanks I guess you are right. It seems to work now.

My original .gnuplot file:
`
#!/usr/bin/gnuplot -persist
print "Configuration loaded !!"
# blue line and blue bullets
set style line 1 lt 1 lw 1 pt 7 linecolor rgb "blue"
set term x11
`

raised an error after
`gp.plot((x,y,{'with':'p ls 1'}))`

    GnuplotlibError: Gnuplot error: ' 
    Configuration loaded !!
    ' while sending cmd 'set terminal push'

After I have commented out the `print "Configuration loaded !!" ` line, the error disappeared, but the points plotted were red crosses instead of blue bullets.

However, I just restarted ipython and now it works. 

Btw., the library doesn't work with older versions of numpy. I just tried it with numpy-1.8 but there is no numpy.moveaxis() function available. With numpy-1.10 it works well.

**Comment by dkogan** [comment]
steview2000 <notifications@github.com> writes:

> Thanks I guess you are right. It seems to work now.
>
> My original .gnuplot file:
> `
> #!/usr/bin/gnuplot -persist
> print "Configuration loaded !!"
> # blue line and blue bullets
> set style line 1 lt 1 lw 1 pt 7 linecolor rgb "blue"
> set term x11
> `
>
> raised an error after
> `gp.plot((x,y,{'with':'p ls 1'}))`
>
>     GnuplotlibError: Gnuplot error: ' 
>     Configuration loaded !!
>     ' while sending cmd 'set terminal push'

Thanks for tracking this down. I can easily imagine the print confusing
it. I'll fix it when I get the chance, or you can submit a patch.


> After I have commented out the `print "Configuration loaded !!" `
> line, the error disappeared, but the points plotted were red crosses
> instead of blue bullets.

Interesting. Not 100% sure what's going on here, but it could be a bug.
Again, I'll look into it at some point.


> Btw., the library doesn't work with older versions of numpy. I just
> tried it with numpy-1.8 but there is no numpy.moveaxis() function
> available. With numpy-1.10 it works well.

OK. I can fix it, but it this important? Are you (or others) stuck on
numpy 1.8 for some reason?

Thank you for the report.

**Comment by steview2000** [comment]
> OK. I can fix it, but it this important? Are you (or others) stuck on
numpy 1.8 for some reason?

At my work I have Linux Mint 17.1 Rebecca, which I think is the current LTS release. This comes with numpy 1.8. However, now I have upgraded to numpy 1.10. So the problem is solved for me.

**Comment by dkogan** [comment]
I don't have cycles to deal with this, so I'm closing the report. If somebody wants to support ancient numpy releases, feed me patches please.
